name: ChangeLog

on:
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: Find changed-files
    outputs:
      changes: ${{ steps.file-changes.outputs.changes }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - uses: tj-actions/changed-files@v35
        name: Changed Files
        id: changed-files
        with:
            since: "7 days"
            files: |
              *.md
      - name: Get changes in files
        id: file-changes
        run: |

          file_change=""
          json="{\"changes\":["
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
            file_change=$(git log --since="3 days" -p $file)

            file_change="${file_change//'%'/'%25'}"
            file_change="${file_change//$'\n'/'%0A'}"
            file_change="${file_change//$'\r'/'%0D'}"
            file_change="${file_change//':'/'%3A'}"
            file_change="${file_change//'<'/'%3C'}"
            file_change="${file_change//'>'/'%3E'}"
            file_change="${file_change//'"'/'%22'}"
            file_change="${file_change//'['/'%5B'}"
            file_change="${file_change//']'/'%5D'}"
            file_change="${file_change//'{'/'%7B'}"
            file_change="${file_change//'}'/'%7D'}"
            file_change="${file_change//'\'/'%5C'}"


            json+="{\"file\":\"$file\", \"change\":\"$file_change\"},"
          done
          json+="]}"

          echo "$json"

          echo "changes=$json" >> $GITHUB_OUTPUT

  summary:
    runs-on: ubuntu-latest
    name: summary
    needs: scan
    strategy:
      matrix: ${{ fromJson(needs.scan.outputs.changes) }}
    steps:
      - name: Print Changes
        id: print-changes
        run: |
          echo "${{ matrix.changes.file}}"
          echo "${{ matrix.changes.change}}"

      - name: Create Summary Completion Jobs
        uses: austenstone/openai-completion-action@v2
        id: create-summary
        with:
          prompt: "As an author of a site called for Microsoft partners called the PartnerCrucible, summarize the additions based on the following git diff output. Provide links to the added references. For relative links, add the base https://lagimik.github.io/PartnerCrucible/ ${{ matrix.changes.change}}"
          max_tokens: 100
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
       
      - name: Print Summary Completion
        id: print-summary
        uses: actions/github-script@v5
        with:
          script:  console.log(JSON.parse('${{ steps.create-summary.outputs.response }}').choices[0].message.content)

     
        