name: ChangeLog

on:
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest  # windows-latest | macos-latest

    name: Find changed-files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.
          
      - uses: tj-actions/changed-files@v35
        name: Changed Files
        id: changed-files
        with:
            since: "7 days"

      - name: Get changes in files
        id: file-changes
        run: |
          $file_changes=()
          $file_change = ""
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
            $file_change = $(git log --since="7 days" -p $file)
            $file_changes += (file_change)
          done
          echo "::set-output name=changes::${file_changes[@]}"
 
  summary:
    needs: scan
    runs-on: ubuntu-latest
    name: Summary
    steps:
      - name: Get file changes
        run: |
          for change in ${{ steps.changed-files.outputs.changes }}; do
            echo "$change"
          done