name: ChangeLog

on:
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest  # windows-latest | macos-latest

    outputs:
      file_changes: ${{ steps.file-changes.outputs.changes }}

    name: Test changed-files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.
          
      - uses: tj-actions/changed-files@v35
        name: Changed Files
        id: changed-files
        with:
            since: "7 days"

      - name:  get changes in files
        id: file-changes
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
            echo "changes=`git log --since="7 days" -p $file`" >> "$GITHUB_OUTPUT"
          done
  summary:
    needs: scan
    runs-on: ubuntu-latest
    name: Summary
    steps:
      - name: Get file changes
        run: |
          echo "${{ steps.file-changes.outputs.changes }}"
            
        
