name: GenerativeCrucible

on:
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: Find changed-files
    outputs:
      changes: ${{ steps.file-changes.outputs.changes }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      # pass vars.CRUCIBLE_HISTORY to github action
      - name: Set History
        id: set-history
        run: |
          echo "CRUCIBLE_HISTORY=${{ vars.CRUCIBLE_HISTORY }}" >> $GITHUB_OUTPUT

      - uses: tj-actions/changed-files@v44
        name: Changed Files
        id: changed-files

        with:
            since: ${{ steps.set-history.outputs.CRUCIBLE_HISTORY }}}
            files: |
              **.md

      - name: Get changes in files
        id: file-changes
        env:
          CRUCIBLE_HISTORY: ${{ steps.set-history.outputs.CRUCIBLE_HISTORY }}}
        run: |
          file_change=""
          json="{\"changes\":["
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
            file_change=$(git log --since="$CRUCIBLE_HISTORY" -p -U0 $file)

            file_change="${file_change//'%'/'%25'}"
            file_change="${file_change//$'\n'/'%0A'}"
            file_change="${file_change//$'\r'/'%0D'}"
            file_change="${file_change//':'/'%3A'}"
            file_change="${file_change//'<'/'%3C'}"
            file_change="${file_change//'>'/'%3E'}"
            file_change="${file_change//'"'/'%22'}"
            file_change="${file_change//'['/'%5B'}"
            file_change="${file_change//']'/'%5D'}"
            file_change="${file_change//'{'/'%7B'}"
            file_change="${file_change//'}'/'%7D'}"
            file_change="${file_change//'\'/'%5C'}"


            json+="{\"file\":\"$file\", \"change\":\"$file_change\"},"
          done
          json+="]}"

          echo "$json"

          echo "changes=$json" >> $GITHUB_OUTPUT

  summary:
    runs-on: ubuntu-latest
    name: summary
    needs: scan
    continue-on-error: true
    outputs:
      completion: ${{ steps.extract-print.outputs.completion }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.scan.outputs.changes) }}
    steps:

      - name: Run Date
        id: run-date
        run: |
          echo "rundate=`date +%Y-%m-%d`" >> $GITHUB_OUTPUT


      - name: Print Changes
        id: print-changes
        run: |
          echo "${{ matrix.changes.file}}"
          echo "${{ matrix.changes.change}}"

      - name: Summary stagger
        id: summary-stagger
        uses: m3y/random-wait-action@v1
        with:
          max-wait-time: 30

      - name: Create Summary Completion Jobs
        if: ${{ (matrix.changes.change != null)  }}
        uses: austenstone/openai-completion-action@main
        id: create-summary
        with:
          prompt: |
            "Use an professional tone to summarize the changes found below in the Partner Crucible updates to help Microsoft Partners Build their technical practice."
            "Use the solution areas as a title heading"
            "Create a list of all the changes. Be brief. Use emojis for emphasis"
            "Next, provide a list of URL links and include the description and source.
            "Format the output as MarkDown."
            "Example"
            "# Heading Solution Area"
            "## What's new"
            "list of changes"
            "## Deep links"
            "- [link title](link url): description (source)"

            "${{ matrix.changes.change}}"
          model: "gpt-4.1-2025-04-14"
          max_tokens: 1000
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Extract Completion and Create ChangeLog
        if: ${{ (matrix.changes.change != null) }}
        id: extract-print-summary
        env:
          FILENAME: ${{ matrix.changes.file}}
          MARKDOWN_FILENAME: ${{ matrix.changes.file}}-changelog.md
          SUMMARY: ${{ fromJson(steps.create-summary.outputs.response).choices[0].message.content }}
        run: |
          echo $SUMMARY
          echo "" >> $MARKDOWN_FILENAME
          echo $SUMMARY >> $MARKDOWN_FILENAME
          echo "" >> $MARKDOWN_FILENAME
          echo "Visit the extended Partner Crucible page on this [Topic Page](https://lagimik.github.io/PartnerCrucible/${FILENAME%.md}) for more partner resources." >> $MARKDOWN_FILENAME
          echo "" >> $MARKDOWN_FILENAME

      - name: Upload markdown artifact
        id:  upload-markdown-artifact
        if: ${{ (matrix.changes.change != null)  }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.changes.file}}-completion-segments
          path: |
            ./*.md
    

      - name: Create Image Prompt
        id: create-image-prompt
        env:
          FILENAME: ${{ matrix.changes.file}}-changelog.md
        run: |
          echo "prompt=a monochrome and photorealistic  modern urban landscape without letters or words inspired by the sentence : - `head -c 64 $FILENAME | tr '\n' ' ' | tr -c '[:alnum:]' ' ' `." >> $GITHUB_OUTPUT

      - name: Wait for a random amount of time
        uses: m3y/random-wait-action@v1
        with:
          max-wait-time: 90
        
      - name: Generate Image
        id: generate-image
        uses: austenstone/openai-image-generation@main
        with:
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          prompt: ${{ steps.create-image-prompt.outputs.prompt }}

      - name: Download Image
        if: ${{ (matrix.changes.change != null) }}
        id: download-image
        env:
          RUNDATE: ${{ steps.run-date.outputs.rundate}}
          MARKFDOWN_FILENAME: ${{ matrix.changes.file}}-changelog.md
          IMAGE_FILENAME: ${{ steps.run-date.outputs.rundate}}-${{ matrix.changes.file}}-image.png
          IMAGE_URL: ${{ steps.generate-image.outputs.image }}
          IMAGE_MARKDOWN: '![ ${{ matrix.changes.file}} ]( /PartnerCrucible/assets/images/${{ steps.run-date.outputs.rundate}}-${{matrix.changes.file}}-image.png )'
        run: |
          curl -o $IMAGE_FILENAME $IMAGE_URL
          { echo -n $IMAGE_MARKDOWN; cat $MARKFDOWN_FILENAME; } > $MARKFDOWN_FILENAME.new
          mv $MARKFDOWN_FILENAME{.new,}


      - name: Image Resizer Action
        id: image-resizer
        uses: sharadcodes/img-resizer@v1.1
        with:
          image-folder: '.' # This is a Required field & this folder has original images
          new-resolution: '200x200' # This is Required field
          output-folder: "assets/images" # This is Required field & this folder will be used to store resized images

      - name: Upload image and markdown artifact
        id:  upload-image-artifact
        if: ${{ (matrix.changes.change != null)  }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.changes.file}}-completion-segments
          overwrite: true
          path: |
            ./assets/images/
            ./*.md

  newsletter:
    runs-on: ubuntu-latest
    name: Newsletter
    needs: summary

    steps:

      - name: Run Date
        id: run-date
        run: |
         echo "rundate=`date +%Y-%m-%d`" >> $GITHUB_OUTPUT

      - name: Download and Expand Artifact
        id: download-artifact
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: .

      - name: List artifacts
        id: list-artifacts
        run: |
          ls -l .

      - name: Combine Summaries
        id: combine-summaries

        env:
          OUTPUTFILE: _posts/${{ steps.run-date.outputs.rundate}}-GenerativePartnerCrucible.md
          RUNDATE: ${{ steps.run-date.outputs.rundate}}

        run: |
          mkdir _posts

          echo "---" >> $OUTPUTFILE
          echo "title: 'Generative Partner Crucible - for the week ending $RUNDATE'" >> $OUTPUTFILE
          echo "date: $RUNDATE" >> $OUTPUTFILE
          echo "flag: GenerativePartnerCrucible" >> $OUTPUTFILE
          echo "layout: generativepartnercrucible" >> $OUTPUTFILE
          echo "thumbnail: /PartnerCrucible/assets/images/$RUNDATE-PowerPlatformSolutionArea.md-image.png" >> $OUTPUTFILE
          echo "---" >> $OUTPUTFILE

          for file in *changelog.md; do
            echo $file
            cat $file >> $OUTPUTFILE
          done

      - name: Upload stream
        id:  upload-stream
        uses: actions/upload-artifact@v4
        with:
          name: generative-partner-crucible
          path: |
            ./_posts/*.md
            ./assets/images/*.png

  pull-request:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: Pull request
    needs: Newsletter


    steps:

      - name: Run Date
        id: run-date
        run: |
          echo "rundate=`date +%Y-%m-%d`" >> $GITHUB_OUTPUT

      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Download and Expand Artifact
        id: download-artifact
        uses: actions/download-artifact@v4
        with:
          name: generative-partner-crucible
          path: .

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Add Generative Partner Crucible for ${{ steps.run-date.outputs.rundate}}"
          title: "Add Generative Partner Crucible for ${{ steps.run-date.outputs.rundate}}"
          body: "This is an automated pull request to add the Generative Partner Crucible for ${{ steps.run-date.outputs.rundate}}"




